// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/SethukumarJ/CashierX-Auth-Service/pkg/api"
	"github.com/SethukumarJ/CashierX-Auth-Service/pkg/api/handler"
	"github.com/SethukumarJ/CashierX-Auth-Service/pkg/config"
	"github.com/SethukumarJ/CashierX-Auth-Service/pkg/db"
	"github.com/SethukumarJ/CashierX-Auth-Service/pkg/repository"
	"github.com/SethukumarJ/CashierX-Auth-Service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	jwtUsecase := usecase.NewJWTUsecase()
	userHandler := handler.NewUserHandler(userUseCase, jwtUsecase)
	serverHTTP := http.NewServerHTTP(userHandler)
	return serverHTTP, nil
}
